logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:8011
        - 127.0.0.1:8002
        - 127.0.0.1:8003
#    sentinel:
#      master: mymaster
#      nodes:
#        - 127.0.0.1:27001
#        - 127.0.0.1:27002
#        - 127.0.0.1:27003