server:
  port: 8181
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://127.0.0.1:2306/heima?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: 123456
mybatis-plus:
  type-aliases-package: com.heima.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS
canal:
  destination: heima
  server: 127.0.0.1:11111